---
apiVersion: v1
kind: Namespace
metadata:
  name: myns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: myns
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  selector:
    matchLabels:
      app_name: api
      app_version: 0.0.1
  template:
    metadata:
      labels:
        app_name: api
        app_version: 0.0.1
    spec:
      containers:
      - name: api
        image: test-api:__IMAGE_TAG__
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: api-port
        resources:    # We can use Vertical Pod Autoscaler (VPA) to automatically adjust request/limits values
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /hello
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:    
          httpGet:          
            path: /hello
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
        # I don't think we need for a startup probe in this keys    

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: myns
spec:
  selector:
    app_name: api  # This service can be used for different app_version
  type: ClusterIP
  ports:
    - name: api-svc
      protocol: TCP
      port: 3000
      targetPort: api-port