apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-port
      protocol: TCP
      name: api-svc
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
